name: gpt_3_encoder
description: Dart BPE Encoder Decoder for GPT-2 / GPT-3

version: 0.9.0
repository: https://github.com/anasfik/gpt_3_encoder

environment:
  sdk: '>=2.19.6 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
